### ISSUE TITLE
update crate?

### ISSUE THREAD

**Issue by mooreniemi** [richardanaya/emoji-rs#4]
Hey, I tried using this crate expecting the functionality of the #1 merge to be present and it's not. I don't see it on [docs.rs](https://docs.rs/emoji/0.1.1/emoji/?search=lookup_by_name) either. Did you need to push up the new version of the crate?

**Comment by richardanaya** [comment]
Gah, I apologize @Shizcow I completely forgot to publish

**Comment by richardanaya** [comment]
@mooreniemi i'm noticing also that the docs don't show feature flagged items
